name: Pylint

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os-version: ['ubuntu-20.04']
        python-version: [ '3.10' ]
    runs-on: ${{ matrix.os-version }}
    name: test package on ${{ matrix.os-version }} with ${{ matrix.python-version }}
    steps:
      #preparation
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install git+https://github.com/KatherLab/wanshi-utils.git
          pip3 install pylint
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
          continue-on-error: true   
