name: test full

on:
  workflow_dispatch:

jobs:
  full_test:
    strategy:
      fail-fast: false
      matrix:
        os-version: ['ubuntu-20.04','windows-latest','macos-latest']
        python-version: [ '3.10' ]
        include:
          - os-version: 'ubuntu-20.04'
            python-version: '3.6'
          - os-version: 'ubuntu-20.04'
            python-version: '3.7'
          - os-version: 'ubuntu-20.04'
            python-version: '3.8'
          - os-version: 'ubuntu-20.04'
            python-version: '3.9'
    runs-on: ${{ matrix.os-version }}
    name: test package on ${{ matrix.os-version }} with ${{ matrix.python-version }}
    steps:
      #preparation
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install git+https://github.com/KatherLab/wanshi-utils.git
          pip3 install pytest
      #test
      - name: Launch test
        uses: ./.github/actions/test
